PORT: "8080"
ADYEN_HMAC_KEY: "19A1A12013D8FFE8F9A4D668A1F8C0BD9E1A161FF21907F456E2DE2E15085699"
ADYEN_API_KEY: "AQEohmfxKYLOaRJGw0m/n3Q5qf3VbYVbAopTB8AsgaA0ZQUgVmNBbNye1RDBXVsNvuR83LVYjEgiTGAH-UP1nLQ4PYscjjXcs5sW146W/GlWRRc2Fl3yFgPc7wxg=-LT&M%>p8$(.~:Qea"
ADYEN_MERCHANT_ACCOUNT: "Envoyy"
ADYEN_CLIENT_KEY: "test_P2VD4RZUZ5FVZDVWXHBE7AUU6UXCLIRG"
